ceph-salt: by default, apply admin role only to bootstrap node
SUSE/sesdev pull request #443
Opened 2020-08-20 17:49 UTC by smithfarm

The documentation states that the only node that **must** have an
"admin" role is the bootstrap node. On all other nodes, including the
master node, it is an optional role.

Change the default {octopus,ses7,pacific} deployment to use this
minimal configuration. This means we have to ssh to the bootstrap node
in order to run ceph commands.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

2020-08-23 20:18 UTC, smithfarm commented
Probably we need to give "admin" role to the master node by default.

2020-08-24 17:39 UTC, smithfarm commented
This makes the sesdev deployment a little more realistic. By default, `admin` role is mandatory only for nodes that have `bootstrap` and/or `master` role. Also, the user now has control over which nodes get the `admin` role.

2020-08-25 08:48 UTC, ricardoasmarques requested changes
I've created a `pacific` env by running:

```
sesdev create pacific --ceph-salt-repo https://github.com/ceph/ceph-salt.git --ceph-salt-branch master pacific
```

Then I tried to SSH into that cluster, but it fails:

```
# sesdev ssh pacific
Node 'master' does not exist in this deployment

# sesdev list
Found 1 deployment:

+---------+---------+---------+---------------------+
| ID      | Version | Status  | Nodes               |
+---------+---------+---------+---------------------+
| pacific | pacific | running | admin, node1, node2 |
+---------+---------+---------+---------------------+
```

2020-08-25 08:58 UTC, smithfarm commented
@ricardoasmarques Thats strange and unexpected, and I cannot reproduce it here. Somehow this piece of code (which I added a long time ago for backward compatibilty) is being triggered in your case:

https://github.com/SUSE/sesdev/blob/master/seslib/deployment.py#L280-L283

Can you capture the full output of your `sesdev create` command in a file and post it somewhere?

2020-08-25 09:24 UTC, smithfarm commented
@ricardoasmarques I added a commit that should fix the issue for you. It's weird, though - I can't reproduce it.

2020-08-25 10:42 UTC, ricardoasmarques approved these changes
LGTM

2020-08-26 09:40 UTC, merged