Add support for IPv6
SUSE/sesdev pull request #56
Opened 2020-01-23 11:20 UTC by ricardoasmarques

If `--ipv6` option is used, IPv6 addresses will be configured:

![Screenshot from 2020-01-23 11-18-44](https://user-images.githubusercontent.com/14297426/72980336-4e0b2080-3dd2-11ea-851c-3899f7804943.png)

Signed-off-by: Ricardo Marques <rimarques@suse.com>

2020-07-03 03:48 UTC, matthewoliver commented on seslib/templates/provision.sh.j2
> +ssh {{ __node.name }} "echo $IPV6_HOST >> /etc/hosts"
I needed to add " arounf the $IPV6_HOST:

`ssh {{ __node.name }} "echo \"$IPV6_HOST\" >> /etc/hosts"`

2020-07-08 15:33 UTC, ricardoasmarques commented on seslib/templates/provision.sh.j2
> +ssh {{ __node.name }} "echo $IPV6_HOST >> /etc/hosts"
Fixed and rebased.

2020-07-14 04:17 UTC, smithfarm commented
@ricardoasmarques Sorry, over the weekend I merged a somewhat drastic refactoring of everything under `seslib/templates/`. Would you mind rebasing this?

Also, can we drop the DNM now?

2020-07-23 21:23 UTC, smithfarm commented
https://github.com/ceph/ceph/pull/35633 (which looks related) has been merged upstream and has reached ses7 in the meantime.

2020-07-29 23:25 UTC, matthewoliver commented
I'm also working on an addition we can merge into this PR which sets the mon_ip in ceph-salt when --ipv6.

2020-07-30 03:38 UTC, matthewoliver commented
Well currently to this patch all we need to is add:
```
diff --git a/seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2 b/seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
index 536c85a..9a91d9c 100644
--- a/seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
+++ b/seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
@@ -52,6 +52,11 @@ ceph-salt config /ceph_cluster/roles/admin add {{ node.fqdn }}
 {% endif %}
 {% if node.has_role('bootstrap') %}
 ceph-salt config /ceph_cluster/roles/bootstrap set {{ node.fqdn }}
+  {% if ipv6 %}
+IPV6_CMD="ip -6 addr | grep 'scope global dynamic mngtmpaddr' | sed -e 's/.*inet6 \(.*\)\/.*/\1/'"
+IPV6_ADDR="$(ssh {{ node.name }} $IPV6_CMD)"
+ceph-salt config /cephadm_bootstrap/mon_ip set "[$IPV6_ADDR]"
+  {% endif %}
 {% endif %}
 {% endfor %}
```
So the mon-ip is set when we use `--ipv6`
But did find another cephadm bootstrap problem in testing this. So this PR will need to land before we can say it works for sesdev: https://github.com/ceph/ceph/pull/36360

2020-07-30 05:15 UTC, smithfarm commented
@ricardoasmarques @matthewoliver I added a checklist to the PR description. Feel free to update it, correct it, delete it, add to it, as you see fit :-)

2020-07-30 08:16 UTC, ricardoasmarques commented
Thanks @matthewoliver, I've now rebased the PR and applied your patch.

2020-08-13 12:43 UTC, ricardoasmarques commented
This is not working yet due to https://tracker.ceph.com/issues/46922

2020-09-15 15:40 UTC, ricardoasmarques commented
I was now able to deploy a cluster using IPv6:

```
# sesdev create pacific --ceph-salt-repo https://github.com/ceph/ceph-salt.git --ceph-salt-branch master --ipv6 pacific-ipv6
...

master:~ # ceph-salt config /cephadm_bootstrap/mon_ip ls
o- mon_ip .................................................................................... [[fde4:8dba:82e1:0:5054:ff:fef5:f8b]]

master:~ # ceph-salt apply
...

master:~ # ceph -s
  cluster:
    id:     84af9658-f762-11ea-ae63-525400a31de4
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum node1,node3,node2 (age 41m)
    mgr: node1.alfrkp(active, since 39m), standbys: node3.rvxsee, node2.zwqsmf
    mds: sesdev_fs:1 {0=sesdev_fs.node3.uyjofk=up:active} 1 up:standby
    osd: 6 osds: 6 up (since 40m), 6 in (since 40m)
    rgw: 2 daemons active (default.default.node1.bxmxku, default.default.node3.clbrdi)
 
  data:
    pools:   9 pools, 233 pgs
    objects: 222 objects, 8.2 KiB
    usage:   109 MiB used, 48 GiB / 48 GiB avail
    pgs:     233 active+clean
 
  io:
    client:   255 B/s rd, 0 op/s rd, 0 op/s wr
```

2020-09-15 15:48 UTC, smithfarm commented
@ricardoasmarques Could you add an `--ipv6` test case to the `pacific` conditional block in `contrib/standalone.sh` please?

2020-09-15 15:56 UTC, smithfarm commented on seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
> -
please reinstate this blank line - I put it there on purpose :-)

2020-09-15 16:07 UTC, smithfarm commented on seslib/templates/provision.sh.j2
>  {% endif %}
please back out this whitespace-only change

2020-09-15 19:04 UTC, smithfarm commented on seslib/templates/salt/provision.sh.j2
> +IPV6_HOST="`bash -c "$IPV6_CMD"` {{ _node.fqdn }} {{ _node.name }}"
please replace the backticks with `$( ... )`

2020-09-15 19:04 UTC, smithfarm commented on seslib/templates/salt/provision.sh.j2
> +IPV6_HOST="`ssh {{ _node.name }} $IPV6_CMD` {{ _node.fqdn }} {{ _node.name }}"
please replace the backticks with `$( ... )`

2020-09-15 19:06 UTC, smithfarm commented on seslib/templates/salt/provision.sh.j2
> +{% endif %}
please put `{# ... #}` comments after all the `endif` statements for better orientation in the code

2020-09-15 21:05 UTC, ricardoasmarques commented
We may need to run `# sysctl -w net.ipv6.conf.all.accept_ra=2` on Jenkins/CI.

2020-09-16 11:06 UTC, smithfarm commented
> @smithfarm All comments addressed, but we may need to run `# sysctl -w net.ipv6.conf.all.accept_ra=2` on Jenkins/CI.

Jenkins is not running `sesdev create octopus` with the `--ipv6` option, so I don't think it's necessary. The Jenkins/CI failures should be fixed now that  #482 has been merged.

2020-09-16 12:11 UTC, smithfarm approved these changes

2020-09-16 12:51 UTC, smithfarm requested changes
#482 added the following line to `seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2`:

```
ceph-salt config /cephadm_bootstrap/mon_ip set {{ bootstrap_mon_ip }}
```

Could you please

1. rebase the PR on tip of SUSE/sesdev master branch
2. move that line up into your `{% if ipv6 %}` conditional (add an `{% else %}` branch)

Otherwise, we will have two conflicting `ceph-salt config /cephadm_bootstrap/mon_ip` calls.

2020-09-17 14:39 UTC, ricardoasmarques commented
> ...
> Otherwise, we will have two conflicting `ceph-salt config /cephadm_bootstrap/mon_ip` calls.

Nice catch! Fixed.

2020-09-17 15:35 UTC, smithfarm approved these changes

2020-09-17 17:16 UTC, smithfarm commented
I wonder what it actually means to create an IPv6 cluster using the PR? For example, should we provide an IPv6 address here:

```
    master: ++ ceph-salt config /time_server/subnet set 10.20.16.0/24
    master: Value set.
```

2020-09-17 17:18 UTC, smithfarm commented
OK, I see with this PR `/etc/hosts` gives IPv6 as well as IPv4 addresses for each host:

```
10.20.16.200 master.pacific-1node-ipv6.test master
fde4:8dba:82e1:0:5054:ff:fe24:dfcd master.pacific-1node-ipv6.test master
```

2020-09-17 17:20 UTC, smithfarm commented
One more thing I noticed is that the interface actually has **two** IPv6 adresses:

```
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:24:df:cd brd ff:ff:ff:ff:ff:ff
    inet 10.20.16.200/24 brd 10.20.16.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fde4:8dba:82e1:0:7592:ca61:7fc8:b29d/64 scope global temporary dynamic 
       valid_lft 3227sec preferred_lft 3227sec
    inet6 fde4:8dba:82e1:0:5054:ff:fe24:dfcd/64 scope global dynamic mngtmpaddr 
       valid_lft 3227sec preferred_lft 3227sec
    inet6 fe80::5054:ff:fe24:dfcd/64 scope link 
       valid_lft forever preferred_lft forever
```

2020-09-17 20:08 UTC, smithfarm commented
This appears to break `contrib/standalone.sh --pacific` - `cephadm bootstrap` returns an error. From `/var/log/ceph/cephadm.log`:

```
DEBUG:cephadm:Running command: /usr/bin/podman run --rm --net=host --ipc=host -e CONTAINER_IMAGE=registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph -e NODE_NAME=master -v /tmp/ceph-tmpiigq6fkv:/tmp/monmap:z --entrypoint /usr/bin/monmaptool registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph --create --clobber --fsid 14ef9f1e-f921-11ea-a289-5254006c698f --addv master [v2:fde4:8dba:82e1:0:5054:ff:fe08:6cd:3300,v1:fde4:8dba:82e1:0:5054:ff:fe08:6cd:6789] /tmp/monmap
DEBUG:cephadm:/usr/bin/monmaptool:profile rt=0.3167150020599365, stop=False, exit=None, reads=[10]
DEBUG:cephadm:/usr/bin/monmaptool:stderr /usr/bin/monmaptool: invalid ip:port '[v2:fde4:8dba:82e1:0:5054:ff:fe08:6cd:3300,v1:fde4:8dba:82e1:0:5054:ff:fe08:6cd:6789]'
DEBUG:cephadm:/usr/bin/monmaptool:profile rt=0.31722235679626465, stop=False, exit=None, reads=[10]
DEBUG:cephadm:/usr/bin/monmaptool:profile rt=0.4042174816131592, stop=False, exit=255, reads=[8, 10]
DEBUG:cephadm:/usr/bin/monmaptool:profile rt=0.40442609786987305, stop=True, exit=255, reads=[8, 10]
INFO:cephadm:Non-zero exit code 255 from /usr/bin/podman run --rm --net=host --ipc=host -e CONTAINER_IMAGE=registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph -e NODE_NAME=master -v /tmp/ceph-tmpiigq6fkv:/tmp/monmap:z --entrypoint /usr/bin/monmaptool registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph --create --clobber --fsid 14ef9f1e-f921-11ea-a289-5254006c698f --addv master [v2:fde4:8dba:82e1:0:5054:ff:fe08:6cd:3300,v1:fde4:8dba:82e1:0:5054:ff:fe08:6cd:6789] /tmp/monmap
INFO:cephadm:/usr/bin/monmaptool:stderr /usr/bin/monmaptool: invalid ip:port '[v2:fde4:8dba:82e1:0:5054:ff:fe08:6cd:3300,v1:fde4:8dba:82e1:0:5054:ff:fe08:6cd:6789]'
Traceback (most recent call last):
  File "/usr/sbin/cephadm", line 5742, in <module>
    r = args.func()
  File "/usr/sbin/cephadm", line 1214, in _default_image
    return func()
  File "/usr/sbin/cephadm", line 2676, in command_bootstrap
    tmp_monmap.name: '/tmp/monmap:z',
  File "/usr/sbin/cephadm", line 2419, in run
    self.run_cmd(), desc=self.entrypoint, timeout=timeout)
  File "/usr/sbin/cephadm", line 875, in call_throws
    raise RuntimeError('Failed command: %s' % ' '.join(command))
RuntimeError: Failed command: /usr/bin/podman run --rm --net=host --ipc=host -e CONTAINER_IMAGE=registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph -e NODE_NAME=master -v /tmp/ceph-tmpiigq6fkv:/tmp/monmap:z --entrypoint /usr/bin/monmaptool registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph --create --clobber --fsid 14ef9f1e-f921-11ea-a289-5254006c698f --addv master [v2:fde4:8dba:82e1:0:5054:ff:fe08:6cd:3300,v1:fde4:8dba:82e1:0:5054:ff:fe08:6cd:6789] /tmp/monmap
```

2020-09-18 17:24 UTC, smithfarm commented on sesdev/__init__.py
> +    settings_dict['ipv6'] = ipv6
This will cause the `ipv6` setting to be unconditionally set to "None" for deployment versions that do not have the ipv6 option. I would rather not set it all in that case. Therefore, please change this line to:

```
if ipv6 is not None:
    settings_dict['ipv6'] = ipv6
```

(This will make it consistent with the way we are populating the other keys of `settings_dict`. When the setting is not set at all, it will get the default value specified in `seslib/settings.py`.)

2020-09-18 17:44 UTC, smithfarm commented on sesdev/__init__.py
> +    settings_dict['ipv6'] = ipv6
NOTE: I went ahead and made this change myself, so this PR can now be merged.

2020-09-18 17:44 UTC, merged