feature: mixed disk drive layouts
SUSE/sesdev pull request #653
Opened 2022-05-25 13:14 UTC by m-ildefons

Provision mixed disk drive layouts when specifying `--num-disks` and
`--disk-size` multiple times.

fixes: #652
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

2022-07-12 13:35 UTC, kshtsk commented on seslib/deployment.py
> +                node.storage_disks.append(Disk(self.settings.disk_size[_i]
What happens disk_size length is less than `num_disks`?

2022-07-12 13:36 UTC, kshtsk requested changes
I don't think it is ready to merge yet.

2022-08-02 18:39 UTC, kshtsk commented
jenkins retest this please

2022-08-03 06:42 UTC, m-ildefons commented on seslib/deployment.py
> +                node.storage_disks.append(Disk(self.settings.disk_size[_i]
I wasn't aware that the `foo[bar] or buzz` syntax doesn't work with lists. AFAIK it works with dicts though. Fixed it.

2024-08-29 09:43 UTC, closed without merging