feature: generate maintentance test reports
SUSE/sesdev pull request #656
Opened 2022-07-07 14:32 UTC by m-ildefons

- Add command for generating maintenance test report data on a running
  cluster.

When testing maintenance updates for various packages, certain
informations need to be collected and entered into the final report.
Thus far, the information was largely collected by hand from various
commands run against the cluster.

This change adds a new sub command, which aggregates this information
and prints it ready for copy-and-paste to the console.
Included in this information is
 - The command and configuration used to create the test cluster
 - Basic information about the resulting cluster layout
 - A list of packages and installation statuses from each relevenat
   repo on each host
 - The Ceph cluster status

Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

2022-07-12 13:30 UTC, kshtsk commented on seslib/deployment.py
> +    def list_packages_from_repo(self, repo):
For generality refactor the function to `list_packages` with optional _repo_ argument, which returns all packages for all repos?

2022-07-12 13:33 UTC, kshtsk commented on seslib/deployment.py
> +    def list_packages_from_repo(self, repo):
Also, the function lacks of description, and I guess it should return a dictionary of nodes to list of package names rather than list of lines of output from zypper command execution.

2022-07-12 13:34 UTC, kshtsk requested changes
See comments above.

2022-07-14 07:23 UTC, m-ildefons commented on sesdev/__init__.py
> +    """
`status` exists already. `report` may be a good idea, but this is report specialized to the needs of the QA maintenance workflow.

2022-07-14 07:27 UTC, m-ildefons commented on seslib/deployment.py
> +    def list_packages_from_repo(self, repo):
I'd like to avoid constructing very generalized functions when they are not needed. Also I'd like to avoid parsing `zypper` output. I'll see if I can fetch the data in a machine-friendly format like JSON...

2022-07-14 10:44 UTC, kshtsk commented on seslib/deployment.py
> +    def list_packages_from_repo(self, repo):
@m-ildefons but you're doing the parsing already in the `__init__` module, all I say it is to bring it here and make the code more functional.

2022-07-14 10:53 UTC, kshtsk commented on sesdev/__init__.py
> +    """
From what I see in the description of the function, there is nothing specific, what not be useful for the other deployment.

2022-07-14 10:56 UTC, kshtsk commented on seslib/deployment.py
> +    def list_packages_from_repo(self, repo):
And by the way, the unit test for this function would be excellent accompaniment.

2022-07-21 13:52 UTC, kshtsk commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
Looks good, but maybe move this code to zypper module?

2022-07-21 13:54 UTC, kshtsk commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
and a unit test for parsing package names from zypper output?

2022-07-21 16:05 UTC, m-ildefons commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
I'd like to keep the code in the deployment module because it operates on a deployments private data.

I haven't added unit tests for one simple reason, the call to zypper and the parsing are tied together, because the parser function expects the zypper output in a format specific to this call. Therefore unless I am to fake out a ssh connection, there really is no good way to unit test this function and that is very hard to do for code that sees this little use. We don't need NASA level code quality here.

2022-07-21 21:01 UTC, kshtsk commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
It is logical to place zipper output parsing code in zipper module, since it is universal. It is not about adding full coverage for NASA type code quality, just basic parsing thing that makes it simple to verify the code without deploying the stuff, the easiest way is to mock the ssh call or isolate the parsing code from the calls ssh.

2022-07-22 07:43 UTC, m-ildefons commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
It is *not* universal. The parsing code assumes that the output of zypper is in a special non-default format. Therefore the parsing code depends on the details of the ssh call.
It is also not universal because other zypper subcommands will produce other formats, which it will not parse either.

All I want is a list of packages from the specified repos and their installation status/version and I want that in the report. I would even take the output of zypper verbatim (which was my first implementation of this). I don't want to write universal zypper output parsers and I don't want to write code that someone might re-use (which is highly unlikely given the state of SES). The zypper module is a stub and I'd like to keep it that way because writing python bindings for zypper is nice, but out of scope for this project.

2022-07-22 13:10 UTC, kshtsk commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
> It is _not_ universal. The parsing code assumes that the output of zypper is in a special non-default format. Therefore the parsing code depends on the details of the ssh call. It is also not universal because other zypper subcommands will produce other formats, which it will not parse either.

From my point of view it is universal when it comes to get a list of packages on from any node where zypper is installed.
And thus there should be a test coverage for the code which is parsing the output for that set of options for zypper. Since it is parsing output from the zypper, it is natural to put it in zypper module, there is nothing specific to a deployment. The list_packages could be left in deployment but only as a proxy call to responding zypper, for example, static methods.

2022-07-22 13:11 UTC, kshtsk commented
And by the way when we done with addressing hints to the PR it is better to squash all the commits within it before merging.

2022-07-22 14:39 UTC, m-ildefons commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
Read the code:
```python
self._ssh_cmd(node)
```
is not accessible outside of the context of a deployment. The functionality of `list_packages` is tightly coupled to deployments. And the functionality of `_to_package_list` is coupled to specific zypper options. It would be a bad idea to bend over backwards in order to decouple the code and be able to insert unit tests (which btw amount to nothing more than making sure pythons `str.split()` works.

You can make a case out of missing support for ubuntu based deployments, but then again that is irrelevant for what I intend with this PR.

2022-07-26 11:09 UTC, kshtsk commented on seslib/deployment.py
> +            packages[node] = _to_package_list(raw_package_list)
> Read the code:
> 
> ```python
> self._ssh_cmd(node)
> ```
> 
> is not accessible outside of the context of a deployment. The functionality of `list_packages` is tightly coupled to deployments. And the functionality of `_to_package_list` is coupled to specific zypper options. It would be a bad idea to bend over backwards in order to decouple the code and be able to insert unit tests (which btw amount to nothing more than making sure pythons `str.split()` works.
> 
I can see what you're trying to say, but I don't think it is THAT bad idea. Alternatively you might use mocking, but decoupling looks easier to refactor the code. Although embedded functions is a great mechanism, but only for some simple piece of code, the bad thing is that it is impossible to test them, so more or less complicated unit should be decoupled. 
It is not only how split works, it is also, which indexes for table records and for which arguments do use it for ZypperPackage, also it is about different skipping code you've been using.

> You can make a case out of missing support for ubuntu based deployments, but then again that is irrelevant for what I intend with this PR.

No, we don't care about Ubuntu here at all now, and RedHat neither.

2022-08-01 14:48 UTC, kshtsk commented on seslib/deployment.py
> +    def list_packages(self, repos=None):
Still needs to be covered with unit tests.

2022-08-02 12:32 UTC, asettle commented
> And by the way when we done with addressing hints to the PR it is better to squash all the commits within it before merging.

This has been open for far too long. Let's squash, and merge. I appreciate that the unit tests are best practice, but sesdev can't be taking this much time from the both of you. 

We can revisit this and the need unit tests if the time arises.

2022-08-08 14:40 UTC, kshtsk approved these changes
ok for now

2022-08-09 07:57 UTC, merged