Add ability to deploy Longhorn on k3s
SUSE/sesdev pull request #692
Opened 2023-04-19 08:23 UTC by tserong

This adds the `--deploy-longhorn` option to `sesdev create k3s`, which will make sesdev deploy Longhorn instead of Ceph.  By default it will deploy the latest released version of Longhorn on SLE 15 SP3, but this can be overridden by using the `--longhorn-version` and `--os options` respectively.
    
When deploying Longhorn, one extra 8GB disk will be added to each worker node mounted as ext4 under /var/lib/longhorn.  One possible area for future work is to make it use multiple disks per node.
    
The Longhorn UI will be made available via HTTP with no authentication.

2023-04-19 08:45 UTC, kshtsk commented on sesdev/__init__.py
> +    Creates a k3s cluster using Tumbleweed by default, or SLE 15 SP3
the sp3 looks super old, maybe sp5 now?

2023-04-19 08:51 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
This is really not good idea, since rest api has limited number of requests, as we saw on our CI jobs it may block everything.

2023-04-19 09:01 UTC, m-ildefons requested changes
There are two places where I'm not convinced this code is sufficiently robust:
- `sesdev create k3s` without any more options doesn't seem to default to the same base os
- explicitly setting the number of disks may give unexpected results if `--num-disks` is not exactly one.

2023-04-19 09:06 UTC, tserong commented on sesdev/__init__.py
> +    Creates a k3s cluster using Tumbleweed by default, or SLE 15 SP3
Well, SP5 isn't released yet...  SP3 is there because I started earlier from the perspective of deploying Ceph via Rook, and in a SES 7.1 context that meant SP3. But you're right, SP3 is getting a bit old.

2023-04-19 09:07 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
I'm open to suggestions for another way of finding out the latest longhorn release.

2023-04-19 09:09 UTC, tserong commented on sesdev/__init__.py
> +        kwargs['os'] = 'sles-15-sp3'
Hrm. Maybe I should just not mess with the default os (in which case it will be tumbleweed if not specified) and let the user declare what they want explicitly with `--os`?

2023-04-19 09:10 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +echo "/dev/vdb /var/lib/longhorn ext4 defaults 0 2" >> /etc/fstab
Here, I hadn't yet figured out how to do something useful with more than one disk. But you're right, my current implementation is a bit sketchy. I'll fiddle with this a bit more.

2023-04-19 09:11 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
May we have an option for longhorn version as well as k3s version option btw.

2023-04-19 09:14 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
And the latest longhorn release is not always the best version to install as far as I understand :-D Maybe this is stupid, but give hint in --help output where to get needed version. I'm not sure if you want to add this running branch to some regular job, we'll see the same as for rookcheck.

2023-04-19 09:15 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
Oh, also: this code path won't even be exercised by the jenkins jobs at the moment anyway, so... Kinda not really a problem yet :-)

2023-04-19 09:23 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
well, I don't like the situation when I'd need to debug this MS thing again in our open source project :-D
another stupid suggestion from me, just parse out https://github.com/longhorn/longhorn/tags

2023-04-19 09:24 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
Anyway, having this code in remote shell is not good either, just try and do it on python side.

2023-04-19 09:26 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
The fact that this code will never run in CI, other cool guys might block the api, you'll have to debug your code trying to understand why curl is failed.

2023-04-19 10:11 UTC, m-ildefons commented on sesdev/__init__.py
> +        kwargs['os'] = 'sles-15-sp3'
Sounds more reasonable, if the default for a 'bare' k3s is to be installed on tumbleweed. Then I'd not expect that adding a `--deploy-*` flag would change the base os to SLES.
I guess my point here is that it would be quite unexpected to have the `--deploy-*` flag implicitly change the base os compared to the base `sesdev create k3s`

2023-04-19 10:13 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
another reason, why not to do this in shell script, if you are running it on multiple nodes, sequentially it may pick the inconsistent version from git hub, when there is new version appears in the middle

2023-04-19 10:15 UTC, kshtsk commented on sesdev/__init__.py
> +              help='Longhorn version to install (defaults to latest stable)')
Add a hint to the user about version format it consume, for example, it is not obvious that version has 'v' prefix.

2023-04-19 10:16 UTC, kshtsk requested changes
Move the code of getting longhorn version to the python.

2023-04-19 10:18 UTC, m-ildefons commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
I suggest using `helm` to install LH. It defaults to the latest stable release version but you can easily specify a specific version with the `--version` argument. No API queries or parsing or JSON manipulation needed.

That being said, I don't see this method as a hard blocker, since it gets the job done and the edge cases where it fails have little impact and aren't expected to happen a lot, given the user base and use cases of `sesdev` in the first place.

2023-04-19 10:25 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +" | kubectl -n longhorn-system create -f -
I thought we program sesdev in python, why do we do shell here at all?

2023-04-19 10:51 UTC, kshtsk commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
> I suggest using `helm` to install LH. It defaults to the latest stable release version but you can easily specify a specific version with the `--version` argument. No API queries or parsing or JSON manipulation needed.

I like the idea to use helm for it.

> That being said, I don't see this method as a hard blocker, since it gets the job done and the edge cases where it fails have little impact and aren't expected to happen a lot, given the user base and use cases of `sesdev` in the first place.

Though, if we can avoid this now, why not to drop this ugly code? It costs nothing in comparison what we need to do in the future with it, going through debugging and trying to recall why is it happening wasting more time.

2023-04-20 04:54 UTC, tserong commented on sesdev/__init__.py
> +    Creates a k3s cluster using Tumbleweed by default, or SLE 15 SP3
I've gotten rid of the SP3 override, so it will now just default to Tumbleweed. I'll open a separate PR for adding SP4 and/or SP5 support (that's a general change anyway, not specific to this Longhorn work).

2023-04-20 04:56 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
> another reason, why not to do this in shell script, if you are running it on multiple nodes, sequentially it may pick the inconsistent version from git hub, when there is new version appears in the middle

That piece of code only ever runs once on the master node so there's no risk of version drift.

2023-04-20 04:58 UTC, tserong commented on sesdev/__init__.py
> +        kwargs['os'] = 'sles-15-sp3'
Right, I've gotten rid of that weird little bit of magic now :-)

2023-04-20 05:00 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +        https://api.github.com/repos/longhorn/longhorn/releases | \
That said, thanks guys - using helm does seem neater under the circumstances. Let me try that instead...

2023-04-20 05:07 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +echo "/dev/vdb /var/lib/longhorn ext4 defaults 0 2" >> /etc/fstab
Immediately, I've added an extra guard to bail out if `/dev/vdb` doesn't exist.

> I think with longhorn you're supposed to pack all disks that you want LH to use into a LVM and then mount that. 

Yeah, I saw that in the docs but there's also the ability to have longhorn use multiple devices that are on separate mountpoints without LVM, and I wasn't sure which was the most recommended choice, so went with a single device initially just to get something running.

2023-04-20 05:09 UTC, tserong commented on sesdev/__init__.py
> +              help='Longhorn version to install (defaults to latest stable)')
Done

2023-04-20 05:16 UTC, tserong commented on seslib/templates/k3s/provision.sh.j2
> +" | kubectl -n longhorn-system create -f -
That's how sesdev does provisioning for each node. sesdev (written in python) generates a shell script, which is run on each node. The provisioning shell script includes all the commands needed to install and deploy everything.  See https://github.com/SUSE/sesdev/blob/master/seslib/templates/provision.sh.j2, which in turn includes various other scripts from under seslib/templates.

2023-04-21 03:47 UTC, merged